/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAccountRouteImport } from './routes/api/account'
import { Route as ApiAdminRouteImport } from './routes/api/admin'
import { Route as ApiAssignmentsRouteImport } from './routes/api/assignments'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiBillingRouteImport } from './routes/api/billing'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiLegalRouteImport } from './routes/api/legal'
import { Route as ApiLoadsRouteImport } from './routes/api/loads'
import { Route as ApiMessagesRouteImport } from './routes/api/messages'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiOffersRouteImport } from './routes/api/offers'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiTrackingRouteImport } from './routes/api/tracking'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountRoute = ApiAccountRouteImport.update({
  id: '/api/account',
  path: '/api/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssignmentsRoute = ApiAssignmentsRouteImport.update({
  id: '/api/assignments',
  path: '/api/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingRoute = ApiBillingRouteImport.update({
  id: '/api/billing',
  path: '/api/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLegalRoute = ApiLegalRouteImport.update({
  id: '/api/legal',
  path: '/api/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoadsRoute = ApiLoadsRouteImport.update({
  id: '/api/loads',
  path: '/api/loads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesRoute = ApiMessagesRouteImport.update({
  id: '/api/messages',
  path: '/api/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOffersRoute = ApiOffersRouteImport.update({
  id: '/api/offers',
  path: '/api/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackingRoute = ApiTrackingRouteImport.update({
  id: '/api/tracking',
  path: '/api/tracking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/account': typeof ApiAccountRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/assignments': typeof ApiAssignmentsRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/billing': typeof ApiBillingRoute
  '/api/files': typeof ApiFilesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/legal': typeof ApiLegalRoute
  '/api/loads': typeof ApiLoadsRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/offers': typeof ApiOffersRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/tracking': typeof ApiTrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/account': typeof ApiAccountRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/assignments': typeof ApiAssignmentsRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/billing': typeof ApiBillingRoute
  '/api/files': typeof ApiFilesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/legal': typeof ApiLegalRoute
  '/api/loads': typeof ApiLoadsRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/offers': typeof ApiOffersRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/tracking': typeof ApiTrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/account': typeof ApiAccountRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/assignments': typeof ApiAssignmentsRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/billing': typeof ApiBillingRoute
  '/api/files': typeof ApiFilesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/legal': typeof ApiLegalRoute
  '/api/loads': typeof ApiLoadsRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/offers': typeof ApiOffersRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/tracking': typeof ApiTrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/account'
    | '/api/admin'
    | '/api/assignments'
    | '/api/auth'
    | '/api/billing'
    | '/api/files'
    | '/api/health'
    | '/api/legal'
    | '/api/loads'
    | '/api/messages'
    | '/api/notifications'
    | '/api/offers'
    | '/api/profile'
    | '/api/tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/account'
    | '/api/admin'
    | '/api/assignments'
    | '/api/auth'
    | '/api/billing'
    | '/api/files'
    | '/api/health'
    | '/api/legal'
    | '/api/loads'
    | '/api/messages'
    | '/api/notifications'
    | '/api/offers'
    | '/api/profile'
    | '/api/tracking'
  id:
    | '__root__'
    | '/'
    | '/api/account'
    | '/api/admin'
    | '/api/assignments'
    | '/api/auth'
    | '/api/billing'
    | '/api/files'
    | '/api/health'
    | '/api/legal'
    | '/api/loads'
    | '/api/messages'
    | '/api/notifications'
    | '/api/offers'
    | '/api/profile'
    | '/api/tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAccountRoute: typeof ApiAccountRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiAssignmentsRoute: typeof ApiAssignmentsRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiBillingRoute: typeof ApiBillingRoute
  ApiFilesRoute: typeof ApiFilesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiLegalRoute: typeof ApiLegalRoute
  ApiLoadsRoute: typeof ApiLoadsRoute
  ApiMessagesRoute: typeof ApiMessagesRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiOffersRoute: typeof ApiOffersRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiTrackingRoute: typeof ApiTrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account': {
      id: '/api/account'
      path: '/api/account'
      fullPath: '/api/account'
      preLoaderRoute: typeof ApiAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assignments': {
      id: '/api/assignments'
      path: '/api/assignments'
      fullPath: '/api/assignments'
      preLoaderRoute: typeof ApiAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing': {
      id: '/api/billing'
      path: '/api/billing'
      fullPath: '/api/billing'
      preLoaderRoute: typeof ApiBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/legal': {
      id: '/api/legal'
      path: '/api/legal'
      fullPath: '/api/legal'
      preLoaderRoute: typeof ApiLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/loads': {
      id: '/api/loads'
      path: '/api/loads'
      fullPath: '/api/loads'
      preLoaderRoute: typeof ApiLoadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages': {
      id: '/api/messages'
      path: '/api/messages'
      fullPath: '/api/messages'
      preLoaderRoute: typeof ApiMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/offers': {
      id: '/api/offers'
      path: '/api/offers'
      fullPath: '/api/offers'
      preLoaderRoute: typeof ApiOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tracking': {
      id: '/api/tracking'
      path: '/api/tracking'
      fullPath: '/api/tracking'
      preLoaderRoute: typeof ApiTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAccountRoute: ApiAccountRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiAssignmentsRoute: ApiAssignmentsRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiBillingRoute: ApiBillingRoute,
  ApiFilesRoute: ApiFilesRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiLegalRoute: ApiLegalRoute,
  ApiLoadsRoute: ApiLoadsRoute,
  ApiMessagesRoute: ApiMessagesRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiOffersRoute: ApiOffersRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiTrackingRoute: ApiTrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
